### ISSUE TITLE
Begin UI Testing Automation

### ISSUE THREAD

**Issue by foxtrotzulu94** [foxtrot94/McHacksPokedex#18]
_Related to #9 and #7_
Using any of the frameworks for UI automation, create a single test case to open all Activities (Portrait and Landscape) so that future OOM issues can be seen immediately, without interaction.

**Comment by thineshth** [comment]
http://developer.android.com/training/testing/ui-testing/index.html

Starting to set up automated UI tests

More importantly what applies to us is using Espresso as our single app testing framework:
http://developer.android.com/training/testing/ui-testing/espresso-testing.html

**Comment by thineshth** [comment]
Need to establish the user's path through this app to test identify all use cases.
For example:
1)
Action: From Main Page select button with text "Browse Now"
Result: Display Pokedex Activity Page

For these next use cases, might want to repeat for all pokemon in a loop, to make sure no descriptions/sprites cause issues.

2)
Action: Select a Pokemon in Scrolling list
Result: Corresponding Pokemon's descriptions and Sprite is displayed

3) 
Action: Use the Search field to input a number between 1 and 721
Result: Corresponding Pokemon is displayed

4) 
Action: Use the Search field to input a a subset of the Pokemon Name
Result: Corresponding Pokemon are displayed, narrowing down as more text is entered.

...more to come

**Comment by foxtrotzulu94** [comment]
I will help you out with the use cases as soon as we finish dealing with Issue #4 and #12. For now, the only functionality goes as far as the mchacks-original app on the UI front (pending some change in DetailedPokemon Activity)

**Comment by foxtrotzulu94** [comment]
Issue closed due to shifting priorities and time constraints.
