### ISSUE TITLE
Implement Filterable Class

### ISSUE THREAD

**Issue by foxtrotzulu94** [foxtrot94/McHacksPokedex#21]
The PokedexArrayAdapter class was created for displaying custom rows within the ListView. One important feature missing is the ability to filter (search) within the set contained by the array.
Implement the search logic through the Filter class implementation of the array adapter. This is a straightforward comparison operation to discriminate against elements in a set.

**Comment by thineshth** [comment]
Advanced Search portion of filter, needs to filter for:
- Type 1
- Type 2
- Ability
- Generation Available
- Egg Groups 1
- Egg Groups 2
- All 6 Base stats
- The ability to include/exclude Primal/Mega/Alternate Forms
