### ISSUE TITLE
Implement Initial UI

### ISSUE THREAD

**Issue by foxtrotzulu94** [foxtrot94/McHacksPokedex#3]
Implement the frontend of the new system to have a functional application. Such implementation should be as far as the [mchacks-original branch](https://github.com/foxtrot94/ECE-Pokedex/tree/mchacks-original) while focusing on better organization, functionality and responsiveness.

The attached images can be used as reference
![pokedex_interface_gsc](https://cloud.githubusercontent.com/assets/6027890/8636473/97757f02-2830-11e5-9018-a35a539af36b.png)
![pokedexinfo](https://cloud.githubusercontent.com/assets/6027890/8636474/9c0ddf64-2830-11e5-93c6-534e8fae5fae.png)
![coendex](https://cloud.githubusercontent.com/assets/6027890/8636470/885feee4-2830-11e5-9a98-956c12dc48d9.png)

**Comment by thineshth** [comment]
![3-uilandscape](https://cloud.githubusercontent.com/assets/10590901/8764035/15dffa3a-2d8a-11e5-9dd7-bd412c8637bb.png)

Getting no rendering in landscape. Portrait works fine.

(Had to rename the pictures all lowercase for it to build first)

**Comment by foxtrotzulu94** [comment]
Yeap, I just noticed that the commit failed to build. I thought that since the preview rendering component relied on parts of gradle build that it was fault free. Guess I was wrong. Latest commit fixes this.
